name: Rhysd actionlint
description: Check your workflows for common errors, like not declaring outputs before using them, bash script errors, and more!
branding:
  icon: tag
  color: gray-dark
runs:
  using: composite
  steps:
  - name: Add anotation matcher
    run: echo "::add-matcher::actionlint-matcher.json"
    shell: pwsh
    
  - name: Run actionlint
    id: action-lint
    continue-on-error: true
    uses: docker://rhysd/actionlint@sha256:5f957b2a08d223e48133e1a914ed046bea12e578fe2f6ae4de47fdbe691a2468 # 1.6.22
    with:
      args: -color -format "{{json .}}"

  - name: Check outputs
    shell: pwsh
    run: |
      echo "${{ toJson(steps.action-lint.outputs) }}"
      cd ../../_actions/actions/
      ls -la
      
  - name: Docker run    
    shell: pwsh
    run: |                                                                     # 1.6.22
      echo "$pwd"
      ls -la
      #docker run --rm  -v "/home/runner/work/actionlint/actionlint":"/repo" --workdir /repo rhysd/actionlint@sha256:5f957b2a08d223e48133e1a914ed046bea12e578fe2f6ae4de47fdbe691a2468 -color -format "{{json .}}"
      docker run -v /home/runner/work/actionlint/actionlint:/repo --workdir /repo rhysd/actionlint@sha256:5f957b2a08d223e48133e1a914ed046bea12e578fe2f6ae4de47fdbe691a2468

      ls -la
      cd ../../_actions/actions/
      ls -la
