name: Rhysd actionlint
description: Check your workflows for common errors, like not declaring outputs before using them, bash script errors, and more!
branding:
  icon: tag
  color: gray-dark
inputs:
  fail-on-errors:
    description: "Fail the action if errors are found"
    required: false
    default: "true"
outputs:
  results-file:
    description: "Path to the json results of the linter"
    value: ${{ steps.run.outputs.resultsfile }}
    
runs:
  using: composite
  steps:
  - name: Get current rhysd/actionlint version
    shell: bash
    id: getversion
    run: |
      # get actionlintversion from the settings.json file
      actionLintVersion=$(jq -r '.actionlintversion' $GITHUB_ACTION_PATH/settings.json)
      actionlintversiontag=$(jq -r '.actionlintversiontag' $GITHUB_ACTION_PATH/settings.json)
      echo "actionLintVersion=$actionLintVersion">>$GITHUB_OUTPUT
      echo "Found the version of rhysd/actionlint to use [$actionlintversiontag], with SHA [$actionLintVersion]"

  - name: Docker run rhysd/actionlint
    shell: bash
    id: run
    env:
      FAILONERRORS: ${{ inputs.fail-on-errors }}
    run: |
      # execute rhysd/actionlint as a docker container

      # disable pipefail -e -o that is set on the shell script from the runner to prevent exiting when the docker run command fails
      set +e +o pipefail;

      # matcher needed to annotate the PR with comments
      echo "::add-matcher::$GITHUB_ACTION_PATH/actionlint-matcher.json"
      version=${{ steps.getversion.outputs.actionLintVersion }}
      actionLintContainer=rhysd/actionlint@sha256:$version

      # check if version has a value
      if [[ -z "$version" ]]; then
        echo "ActionLint version to use is empty, cannot continue"
        exit 1
      fi
      
      # run again to get a json result
      result=$(docker run -v $GITHUB_WORKSPACE:/repo --workdir /repo $actionLintContainer -color -format "{{json .}}")
      status=$?

      if jq -e . >/dev/null 2>&1 <<<"$result"; then
          echo "Parsed JSON result successfully"
      else
          echo "Failed to parse JSON, or got false/null"

          if [[ $result -ne 'no project was found in any parent directories of ".". check workflows directory is put correctly in your Git repository' ]]; then
            echo "Showing the resulting messages:"
            echo $result
            echo "-------------------------------"
          fi
      fi
      
      echo $result>"actionlint-errors.json"
      echo "resultsfile=actionlint-errors.json">>$GITHUB_OUTPUT
      
      if [[ $status == 0 ]];
      then
        echo "Actionlint had no errors"
      else
        echo "Actionlint found errors"
        if [[ $FAILONERRORS == "true" ]]; then
          echo "Running the docker container directly to show the errors"
          docker run -v $GITHUB_WORKSPACE:/repo --workdir /repo $actionLintContainer -color   
        fi        
      fi

      if [[ $FAILONERRORS == "true" ]];
      then
        exit $status  
      fi