name: Rhysd actionlint
description: Check your workflows for common errors, like not declaring outputs before using them, bash script errors, and more!
branding:
  icon: tag
  color: gray-dark
runs:
  using: composite
  steps:
  - name: Add anotation matcher
    run: echo "::add-matcher::actionlint-matcher.json"
    shell: pwsh
    
  - name: Run actionlint
    id: action-lint
    if: 1 == 2 # disable in favor of calling the image manually
    continue-on-error: true
    uses: docker://rhysd/actionlint@sha256:5f957b2a08d223e48133e1a914ed046bea12e578fe2f6ae4de47fdbe691a2468 # 1.6.22
    with:
      args: -color -format "{{json .}}"

  - name: Check outputs
    shell: pwsh
    run: |
      echo "${{ toJson(steps.action-lint.outputs) }}"
      cd ../../_actions/actions/
      ls -la
      
  - name: Docker run    
    shell: pwsh
    run: |
      # running version 1.6.22 of rhysd/actionlint
      $result = docker run -v /home/runner/work/actionlint/actionlint:/repo --workdir /repo rhysd/actionlint@sha256:5f957b2a08d223e48133e1a914ed046bea12e578fe2f6ae4de47fdbe691a2468
      
      if ($null -eq $result) {
        # fail the step
        echo "Did not find any errors, double check the workflows. Exiting with failure"
        exit 1
      }
      
      $items = @(ConvertFrom-Json $result -Depth 10)
      $found1 = $false
      foreach ($item in $items) { 
        Write-Host $item.message
        Write-Host $item.filepath
        Write-Host $item.line
        
        if ($item.filepath -eq ".github/workflows/test-local-action.yml" -and $item.line -eq 33) {
          $found1 = $true
        }
      }      
      
      if (!$found1){
        echo "Error finding the first expected result. Exiting with failure"
        exit 1
      }
