name: Rhysd actionlint
description: Check your workflows for common errors, like not declaring outputs before using them, bash script errors, and more!
branding:
  icon: tag
  color: gray-dark
inputs:
  fail-on-errors:
    description: "Fail the action if errors are found"
    required: false
    default: "true"
outputs:
  results-file:
    description: "Path to the json results of the linter"
    value: ${{ steps.run.outputs.resultsfile }}
    
runs:
  using: composite
  steps:
  - name: Add annotation matcher for Action Lint to annotate the PR if needed
    run: echo "::add-matcher::actionlint-matcher.json"
    shell: bash
  
  - name: Docker run    
    shell: bash
    id: run
    env:
      FAILONERRORS: ${{ inputs.fail-on-errors }}
    run: |
      # running version 1.6.22 of rhysd/actionlint
      # disable pipefail -e -o that is set on the shell script from the runner to prevent exiting when the docker run command fails
      set +e +o pipefail;

      echo "Workspace:          [$GITHUB_WORKSPACE]"
      echo "GitHub Action path: [$GITHUB_ACTION_PATH]"

      result=$(docker run -v /home/runner/work/actionlint/actionlint:/repo --workdir /repo rhysd/actionlint@sha256:5f957b2a08d223e48133e1a914ed046bea12e578fe2f6ae4de47fdbe691a2468 -color -format "{{json .}}")
      status=$?

      echo $result > "actionlint-errors.json"
      echo "resultsfile=actionlint-errors.json" >> $GITHUB_OUTPUT
      
      if [[ $status == 0 ]];
      then
        echo "Actionlint had no errors"
      else
        echo "Actionlint found errors"
      fi

      if [[ $FAILONERRORS == "true" ]];
      then
        exit $status  
      fi