name: "Approve Dependabot PR's" 
on:
  pull_request:

permissions:
  contents: write
  pull-requests: write
  actions: write
  
jobs:
  dependabot:
    uses: devops-actions/.github/.github/workflows/approve-dependabot-pr.yml@3abe9f6710c33ede76f8a506b2889ee46a2c9646 # main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
