on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

  push:
    paths:
      - .github/workflows/issue-pr-create.yml
  
permissions:
  contents: read

jobs:
  notify:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
        - name: Harden the runner (Audit all outbound calls)
          uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
          with:
            egress-policy: audit

        - env:
            CONTEXT: ${{ toJSON(github.event) }}
          run: |
            echo "$CONTEXT"
           

        - uses: devops-actions/issue-comment-tag@3a605c5f21e15e5b963c866421bf4189bcc32310 # v0.1.10
          with:
            team: ${{ vars.TAG_TEAM }}
            issue: ${{ github.event.issue.number }}
            pr: ${{ github.event.pull_request.number }}
            owner: ${{ github.repository_owner }}
            repo: ${{ github.repository }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
